
import "./globals.css";
import Header from "./_components/Header";




export const metadata = {
  title: "MovieNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="min-h-screen bg-stone-800"
      >
        <header>

        <Header/>
        </header>
       
        <main className="h-full overflow-x-hidden">

        {children}
        </main>
       
      </body>
    </html>
  );
}
